### ISSUE TITLE
Better error message when UTF-8 conversion fails

### ISSUE THREAD

**Issue by fingolfin** [frankluebeck/GAPDoc#29]
I just run into this error message running GAPDoc (latest `git` version) on a certain package manual:
```
Generating documentation in Directory("./doc/")
#I Composing XML document . . .
#I Parsing XML document . . .
#I Checking XML structure . . .
#I Text version (also produces labels for hyperlinks):
#I First run, collecting cross references, index, toc, bib and so on . . .
Error, List Element: <list> must be a list (not a boolean or fail) in
  return ustr![1]; at /Users/mhorn/Projekte/GAP/repos/pkg/GAPDoc/lib/UnicodeTools.gi:556 called from
IntListUnicodeString( str ) at /Users/mhorn/Projekte/GAP/repos/pkg/GAPDoc/lib/UnicodeTools.gi:1137 called from
width( str{[ i .. j - 1 ]} ) at /Users/mhorn/Projekte/GAP/repos/pkg/GAPDoc/lib/Text.gi:760 called from
FormatParagraph( str, len - indlen, f, [ RepeatedString( " ", indlen ), "" ], WidthUTF8String
 ) at /Users/mhorn/Projekte/GAP/repos/pkg/GAPDoc/lib/GAPDoc2Text.gi:413 called from
GAPDoc2TextProcs.MarkAndFormat( ss, "auto", Length( r.root.indent ), r.root.linelength
 ) at /Users/mhorn/Projekte/GAP/repos/pkg/GAPDoc/lib/GAPDoc2Text.gi:461 called from
par( s, a.name ); at /Users/mhorn/Projekte/GAP/repos/pkg/GAPDoc/lib/GAPDoc2Text.gi:484 called from
...  at makedoc.g:11
you can replace <list> via 'return <list>;'
```

The problem boiled down to an encoding issue; `WidthUTF8String` got passed a string it could not handle:
```
gap> str := "L\374beck.";
"L\374beck."
gap> IsUnicodeString(str);
false
gap> Unicode(str, "UTF-8");
fail
gap> WidthUTF8String(str);
Error, List Element: <list> must be a list (not a boolean or fail) in
  return ustr![1]; at /Users/mhorn/Projekte/GAP/repos/pkg/GAPDoc/lib/UnicodeTools.gi:556 called from
IntListUnicodeString( str ) at /Users/mhorn/Projekte/GAP/repos/pkg/GAPDoc/lib/UnicodeTools.gi:1137 called from
<function "WidthUTF8String">( <arguments> )
 called from read-eval loop at *stdin*:6
you can replace <list> via 'return <list>;'
brk>
```

Could we get a better error message here? I.e. catch the `fail` return value of `Unicode` before passing it to `IntListUnicodeString`, and instead invoking `Error` with something helpful?

**Comment by frankluebeck** [comment]
Ok, this error is now catched to provide a better error message.

**Comment by alex-konovalov** [comment]
For cross-reference, this is https://github.com/frankluebeck/GAPDoc/commit/4a146ae9f55910934aac2149583b1997e2c08774 

(@frankluebeck by the way, composing commit message, you could have written in the 3rd line 

    Closes #29

and then this issue would be closed automatically. It helps to anyone (not only @fingolfin now, but also to you in the future) to understand why a change has been made. Even if you do not want to put a reference to an issue in your commit message, it is still nice to put a link to the commit into a comment like "Ok, this error is now catched to provide a better error message, see https://github.com/frankluebeck/GAPDoc/commit/4a146ae9f55910934aac2149583b1997e2c08774" because in this case it will be easier to track the connection between the issue and the commit addressing it.

**Comment by frankluebeck** [comment]
@alex-konovalov: I'm aware of what you are saying. But I will not put any references to github (or even just meaningless numbers) in commit messages, which I think should be self contained.
Also a cross reference doesn't seem necessary in this case (to me).

**Comment by alex-konovalov** [comment]
@frankluebeck I understand that you may not want to put any references to github into commit messages - that's your choice, I was not insisting on that. On the other hand, cross-references in comments greatly ease navigation. For example, if the author of an issue would like to see how the fix has been implemented, pointing them to the exact fix is very helpful.
